### ISSUE TITLE
Authcode

### ISSUE THREAD

**Issue by UnderKoen** [simplyGits/magisterjs-dynamic-authcode#2]
Ik ben nu zelf bezig met een magister API in swift, en heb nu ook een eigen authcode script geschreven. Het viel mij op dat het script dat jullie gebruiken aardig complex is. Ik weet niet of jullie er iets aan hebben maar hier is mijn methode in PHP zodat het over HTTP geladen kan worden. 

[Code](https://gitlab.com/UnderKoen/macistersite/blob/master/authcode.php)
[Api](https://macister.nl/authcode.php)

**Comment by lieuwex** [comment]
Mooie app!!

Dit hebben we overwogen, maar we waren beetje bang voor kleine aanpassingen in de structuur van de javascript broncode. Ik heb zelf daarom gekozen om elk uur met een chromium instance in een docker container de nieuwe authcode op te halen, @tomsmeding heeft echter een fetch script geschreven die je hier in de repo ziet. In principe verwacht ik dat jouw methode ook wel moet blijven werken, maar als het goed is is die van ons net iets meer bestemd tegen aanpassingen van Magister.

Meer servers die de authcode echter publiceren, des te beter.
